#Simples - The only plugin you need
#Made by Chiru

Config:

    SimpleServerWelcome:

        enabled: true

        welcome-message: "&e&kI &a&lWelcome %player_name%! &rThis welcome message, has been created with &6&lSimple Welcome&r!, change this on the &4&lconfig.yml &e&kI"

    chat-format: "{DISPLAY_NAME} : {MESSAGE}"