#Simples - The only plugin you need
#Made by Chiru

Config:

    SimpleServerWelcome:

        enabled: true

        welcome-message: "&e&kI &a&lWelcome %player_name%! &rThis welcome message, has been created with &6&lSimple Welcome&r!, change this on the &4&lconfig.yml &e&kI"

    #Use the following formats for the "chat-format"
    #   {MESSAGE} - The message
    #   {DISPLAY_NAME} - The player's name
    #   {GROUP_PREFIX} - The player's group prefix *this uses Vault, this would be %vault_groupprefix%*
    chat-format: "{GROUP_PREFIX} &7| &r{DISPLAY_NAME} &r: &7{MESSAGE}"