#+ *** *** *** *** *** *** *** *** +
#|                                 |
#|           Simples               |
#|          by - Chiru             |
#|                                 |
#+ *** *** *** *** *** *** *** *** +

Config:

    #This is the prefix for the /broadcast command!
    broadcast: "&7&l[&9&lSimples&7&l] &r&l"

    #Use the following formats for the "chat-format"
    #   {MESSAGE} - The message
    #   {DISPLAY_NAME} - The player's name
    #   {GROUP_PREFIX} - The player's group prefix *this uses Vault, this would be %vault_groupprefix%*

    chat-format: "{GROUP_PREFIX} &7| &r{DISPLAY_NAME} &r: &7{MESSAGE}"

    SimpleServerWelcome:

        enabled: true

        #Displays the default message when the custom isnt enabled
        display-default: false

        #This setting will make the message show up after a certain ammount of logins. / If set to 0 will always show up
        #But if for example you put 5, the message will show up the 6th time you entered
        every: 0

       #If more than one message, the message will be randomized.
        welcome-messages:
            - "&e&kI &a&lWelcome %player_name%! &rThis welcome message, has been created with &6&lSimple Welcome&r!, change this on the &4&lconfig.yml &e&kI"
            - "&aWelcome, &f&l%player_name%! &eThis is another example message!"
            - "&b&lGreetings, %player_name%! &rEnjoy your time here at &d&lExample Server Name&r!, change this on the &4&lconfig.yml"
            - "&9&lAhoy, %player_name%! &rSail the seas of &3&lExample Server Name&r and discover hidden treasures!"
            - "&aHey %player_name%, welcome aboard! Have a great time!"
            - "&eWelcome, %player_name%! Enjoy your stay on our server!, change this on the &4&lconfig.yml"
            - "&6Ahoy, %player_name%! Your presence illuminates our server like a golden block!"

    #For the tab, you can use placeholders and colors, it reloads using the reload plugin, and rejoining!
    tab:

        enabled: true

        #This variable sets the time after each load of the placeholders (dont set this too low)
        seconds: 15

        #For the "name" config use placeholders, if not leave empty to use default
        #Example : "name: "%vault_groupprefix% &7| &r%player_name%""
        name: ""

        header:
            - "&9&lMy Server"
            - ""
            - "&eThis server uses &f: &4&lSimples"
            - "&fThere are &r: &a%server_online% online &fplayers!"
            - ""
        footer:
            - ""
            - "&a&lPING : %player_ping%"
            - "&e&lTPS : %server_tps_1%"

    scoreboard:

        #This variable sets the time after each load of the placeholders (dont set this too low)
        seconds: 15

        title: "&4&lScoreboard"
        values:
            - ""
            - "&a&lStats:"
            - "&eKills: &r%statistic_player_kills%"
            - "&eDeaths: &r%statistic_deaths%"
            - ""
            - "&a&lInfo:"
            - "&rPing: &c%player_ping%"