#+ *** *** *** *** *** *** *** *** +
#|                                 |
#|           Simples               |
#|          by - Chiru             |
#|                                 |
#+ *** *** *** *** *** *** *** *** +

Config:

    #This is the prefix for the /broadcast command!
    broadcast: "&7&l[&9&lSimples&7&l] &r&l"

    #Use the following formats for the "chat-format"
    #   {MESSAGE} - The message
    #   {DISPLAY_NAME} - The player's name
    #   {GROUP_PREFIX} - The player's group prefix *this uses Vault, this would be %vault_groupprefix%*

    chat-format: "{GROUP_PREFIX} &7| &r{DISPLAY_NAME} &r: &7{MESSAGE}"

    SimpleServerWelcome:

        enabled: true

        #This setting will make the message show up after a certain ammount of logins. / If set to 0 will always show up
        every: 0

        welcome-message: "&e&kI &a&lWelcome %player_name%! &rThis welcome message, has been created with &6&lSimple Welcome&r!, change this on the &4&lconfig.yml &e&kI"

    #For the tab, you can use placeholders and colors, it reloads using the reload plugin, and rejoining!
    tab:

        enabled: true

        #This variable sets the time after each load of the placeholders (dont set this too low)
        seconds: 15

        #For the "name" config use placeholders, if not leave empty to use default
        #Example : "name: "%vault_groupprefix% &7| &r%player_name%""
        name: ""

        header:
            - "&9&lMy Server"
            - ""
            - "&eThis server uses &f: &4&lSimples"
            - "&fThere are &r: &a%server_online% online &fplayers!"
            - ""
        footer:
            - ""
            - "&a&lPING : %player_ping%"
            - "&e&lTPS : %server_tps_1%"

    scoreboard:

        #This variable sets the time after each load of the placeholders (dont set this too low)
        seconds: 15

        title: "&4&lScoreboard"
        values:
            - ""
            - "&a&lStats:"
            - "&eKills: &r%statistic_player_kills%"
            - "&eDeaths: &r%statistic_deaths%"
            - ""
            - "&a&lInfo:"
            - "&rPing: &c%player_ping%"