name: Simples
version: '${project.version}'
main: chiru.simples.Simples
api-version: 1.19
author: Chiru
description: The only plugin you need!
softdepend: [PlaceholderAPI]
commands:
  Simples:
    description: Main Command!
    aliases: [ simple ]
  Broadcast:
    description: Broadcast command
    aliases: [ br, broadcast, announce, ann ]
    permission: simples.broadcast
  Home:
    description: Teleports you to your home
    permission: simples.home
  SetHome:
    description: Sets your home
    permission: simples.home.sethome
  DelHome:
    aliases: [ deletehome ]
    description: Deletes your home
    permission: simples.home.delhome
