name: Simples
version: '1.0.3.1'
main: chiru.simples.Simples
api-version: 1.19
author: Chiru
description: The only plugin you need!
softdepend: [PlaceholderAPI]
commands:
  Simples:
    description: Main Command!
    aliases: [ simple ]
  Broadcast:
    description: Broadcast command
    aliases: [ br, broadcast, announce, ann ]
    permission: simples.broadcast
